### ISSUE TITLE
Máscara CPF registrar aluno

### ISSUE THREAD

**Issue by AndersonCruz123** [leonardosal/PAPS_2015-2#34]
Só é possível registrar, se colocar o CPF xxx.xxx.xxx.-xx, se colocar o CPF xxxxxxxxxxx, sem os traços, não é possível fazer o cadastro  no sistema

**Comment by zottoz** [comment]
Consegue cadastrar sem mascara. Alias fiz dois cadastros um com mascara e outro sem.

**Comment by ariloclaudio** [comment]
Corrigido!
