### ISSUE TITLE
 a

### ISSUE THREAD

**Issue by AndersonCruz123** [leonardosal/PAPS_2015-2#35]
a

**Comment by leonardosal** [comment]
@AndersonCruz123 @ariloclaudio professor isso foi cadastrado pelos coordenadores certo? se foi erro de digitação é só os eles corrigirem editando o nome da atividade.

**Comment by zottoz** [comment]
Anais (do latim annales, de annus, "ano") são, tradicionalmente, uma forma concisa de registro da história de um povo ou instituição, originalmente organizada ano a ano.
