### ISSUE TITLE
Cadastro de horas com datas futuras

### ISSUE THREAD

**Issue by larissaneves** [leonardosal/PAPS_2015-2#39]
Ao tentar fazer uma solicitação de horas com datas que ainda irão acontecer ocorreu o seguinte erro:

PHP Notice – yii\base\ErrorException
Trying to get property of non-object

**Comment by leonardosal** [comment]
@ariloclaudio é possível cadastrar uma atividade para uma data futura ?

**Comment by ariloclaudio** [comment]
@leonardosal Não, todas as atividades já devem ter acontecidos e ainda tem a situação de que não pode ter ocorrido antes do estudante entrar no curso (mas essa segunda verificação é feita pela coordenação). Temos que tratar no sistema a primeira situação.

**Comment by leonardosal** [comment]
@ariloclaudio blz vou só tratar o erro e colocar uma mensagem.

**Comment by leonardosal** [comment]
resolvido
