### ISSUE TITLE
Erro no cadastro de solicitação.

### ISSUE THREAD

**Issue by gcarneirobr** [leonardosal/PAPS_2015-2#44]
O erro ocorre após uma tentativa de cadastrar uma solicitação com horas superiores ao limite de horas para um tipo de evento, mas a solicitação é cadastrada. Segue o log mostrado na tela:

Error
PHP Notice – yii\base\ErrorException

Trying to get property of non-object
1. in /var/www/graduacao/controllers/SolicitacaoController.php at line 122
113114115116117118119120121122123124125126127128129130131                $model->solicitante_id = Yii::$app->user->identity->id;
            }
 
            $model->save();
 
            $file = UploadedFile::getInstance($model, 'arquivo');
 
            $file_name = Yii::$app->user->identity->id . '_' . rand(1, 999999);
 
            $file_name = $file_name . '.' . $file->extension;
 
            $model->arquivo = $file;
 
            $file->saveAs('uploads/' . $file_name);
 
            //atualiza os dados do nome no model solicitacao
 
            $model->anexoOriginalName = $file->baseName . '.' . $file->extension ;
 
2. in /var/www/graduacao/controllers/SolicitacaoController.php at line 122 – yii\base\ErrorHandler::handleError(8, 'Trying to get property of non-ob...', '/var/www/graduacao/controllers/S...', 122, ...)
116117118119120121122123124125126127128            $model->save();
 
            $file = UploadedFile::getInstance($model, 'arquivo');
 
            $file_name = Yii::$app->user->identity->id . '_' . rand(1, 999999);
 
            $file_name = $file_name . '.' . $file->extension;
 
            $model->arquivo = $file;
 
            $file->saveAs('uploads/' . $file_name);
 
            //atualiza os dados do nome no model solicitacao
3. app\controllers\SolicitacaoController::actionCreate()
4. in /var/www/graduacao/vendor/yiisoft/yii2/base/InlineAction.php at line 55 – call_user_func_array([app\controllers\SolicitacaoController, 'actionCreate'], [])
5. in /var/www/graduacao/vendor/yiisoft/yii2/base/Controller.php at line 154 – yii\base\InlineAction::runWithParams(['r' => 'solicitacao/create'])
6. in /var/www/graduacao/vendor/yiisoft/yii2/base/Module.php at line 454 – yii\base\Controller::runAction('create', ['r' => 'solicitacao/create'])
7. in /var/www/graduacao/vendor/yiisoft/yii2/web/Application.php at line 84 – yii\base\Module::runAction('solicitacao/create', ['r' => 'solicitacao/create'])
8. in /var/www/graduacao/vendor/yiisoft/yii2/base/Application.php at line 375 – yii\web\Application::handleRequest(yii\web\Request)
9. in /var/www/graduacao/web/index.php at line 12 – yii\base\Application::run()
6789101112 
require(__DIR__ . '/../vendor/autoload.php');
require(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');
 
$config = require(__DIR__ . '/../config/web.php');
 
(new yii\web\Application($config))->run();
 $_GET = [
    'r' => 'solicitacao/create',
];

$_POST = [
    '_csrf' => 'T2JLdVZ5eGIlK3hGNS0rASFRPQ8vEEwkK1odBmYKSAB/Dh1MJjEqLA==',
    'Solicitacao' => [
        'descricao' => 'Participação na SBESC2014',
        'dtInicio' => '03-11-2014',
        'dtTermino' => '07-11-2014',
        'atividade_id' => '9',
        'horasComputadas' => '10',
        'observacoes' => '',
        'status' => 'Aberto',
        'anexo_id' => '0',
        'arquivo' => '',
    ],
];

$_FILES = [
    'Solicitacao' => [
        'name' => [
            'arquivo' => '',
        ],
        'type' => [
            'arquivo' => '',
        ],
        'tmp_name' => [
            'arquivo' => '',
        ],
        'error' => [
            'arquivo' => 4,
        ],
        'size' => [
            'arquivo' => 0,
        ],
    ],
];

$_COOKIE = [
    '_csrf' => '0ed84f5d462bf11fc35ec5c88b7ab8fd21fb001320235ef54ac37446f23e34afa:2:{i:0;s:5:"_csrf";i:1;s:32:"jI33cTScn3vzyi4Fd8Vs0s0b0lV9pHRN";}',
    'PHPSESSID' => 'blgukn9kgdl9ouct22b836jfd3',
];

$_SESSION = [
    '__flash' => [],
    '__id' => 24,
];
Yii Framework
2016-06-28, 18:57:54

Apache/2.4.10 (Debian) PHP/5.6.7-1
Yii Framework/2.0.7-dev

**Comment by leonardosal** [comment]
resolvido
