### ISSUE TITLE
Erro no cadastro de solicitação

### ISSUE THREAD

**Issue by gcarneirobr** [leonardosal/PAPS_2015-2#45]
Cadastro com dados válidos retornando a seguinte mensagem abaixo do campo de horas:

As horas computadas não podem ser maior que 0

**Comment by gcarneirobr** [comment]
Mesma coisa na edição de solicitação

**Comment by leonardosal** [comment]
duplicado com a #41

**Comment by leonardosal** [comment]
resolvido
